### ISSUE TITLE
Link to blogs

### ISSUE THREAD

**Issue by bquintas** [aws-samples/amazon-comprehend-active-learning-framework#1]
Seems the links may have been changed, corrected should be:

https://aws.amazon.com/blogs/machine-learning/active-learning-workflow-for-amazon-comprehend-custom-classification-part-1/

instead of 

https://aws.amazon.com/blogs/machine-learning/active-learning-workflow-for-amazon-comprehend-custom-classification-models-part-1/

**Comment by joysl** [comment]
Fixed Readme, thank you for letting us know
